### ISSUE TITLE
Does not create promotion PRs correctly for PRs with more than 30 changed files

### ISSUE THREAD

**Issue by nielsole** [wayfair-incubator/telefonistka#137]
https://github.com/wayfair-incubator/telefonistka/blob/8f9afcc5a0c93d42d582a3a962d171874991d839/internal/pkg/githubapi/promotion.go#L123C35-L123C35

https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files
default for `PerPage` is 30.

This can lead to promotion PRs being incomplete.

**Comment by Oded-B** [comment]
I'm back from Christmas break! Thanks for the bug report.

Seems simple enough to fix https://github.com/google/go-github?tab=readme-ov-file#pagination
Though I should probably implement it for every list operation I do, might release a fix for this specific API call and then think about the rest later.

**Comment by Ben10k** [comment]
This is still an issue

**Comment by Oded-B** [comment]
I'l try fix this in the comming week
