### ISSUE TITLE
On-demand and scheduled promotions

### ISSUE THREAD

**Issue by Ben10k** [wayfair-incubator/telefonistka#175]
## Problem Statement

Some environments might have strict regulations on when can changes be made, something like a release window.

Let's say we have multiple customers and to some of them we release updates automatically, but there is a client with an agreement to only release on Mondays working hours.
The current work-around is to use telefonistka for all other environments, but omit that specific one entirely, and on Monday morning an engineer checks out the repository, copies the contents from another prod environment into this environment and starts a PR.

## Proposed Solution

There can be multiple solutions for schedules:
1. External scheduler: a scheduled pipeline, or a kubernetes CronJob would trigger telefonistka in either cli-mode, or send a http request towards the running instance of telefonistka, and then telefonistka would find the changes and start a new PR.
2. Internal scheduler: a promotion in the configuration (telefonistka.yaml) would have an additional field that could describe when to trigger itself.

But for on-demand promotions this gets trickier. Internal scheduler would not help here, so only cli-mode or http request looks like a valid solution.

There can be another solution altogether: **long-lived branches and PRs**:
Instead of tracking each change in each promotion path as a separate PR, telefonistka could scan the whole repository once the main branch get updated and have a long lived branch for each promotion - which would include all the changes from the `source` into `target`. Whenever the promotion PR would be merged, telefonistka could open a new one and accumulate all the drift there.
In that case scheduling would no longer be needed, as there would always be PRs with all the drift between environments, and an engineer could just merge it whenever it can be merged.

## Alternatives Considered

Telefonistka can already receive webhooks from GitHub, it should be possible to "fake" the GitHub's webhook request and pass it to telefonistka to trigger this promotion, but it is only a work-around, that we haven't tested.
Another alternative is just doing it manually, which we are already doing.

@Oded-B what are your thoughts?
I'll be happy to work on this issue once we have an agreement.

**Comment by Oded-B** [comment]
My instinct is to go for the smallest, safest change:  "External scheduler" cli-mode, and rely on the features completeness of external scheduling systems like k8s cronjobs and CI/CD SAASs.
This will also be easier to test (if and when I'll add e2e tests :) )
