### ISSUE TITLE
Promote on changes to changes to promotionPaths

### ISSUE THREAD

**Issue by nielsole** [wayfair-incubator/telefonistka#194]
## Problem Statement

We have a relatively dynamic list of clusters. Upon adding a targetPath, there is no way to trigger a promotion to the new  targetPath for all paths in sourcePath/workspace (except whitespace-changing all paths). If one were to manually copy over the workspace to the promotion folders, allow and block lists would not be respected.

## Proposed Solution

Upon changing telefonistka.yaml, telefonistka should create PRs reconciling the telefonistka.yaml with the repo state.
I'm not sure if this should also include folder deletions, as these are easier to do manually (no allow/block lists to consider) and telefonistka kind of has a roll-forward-only notion.

## Alternatives Considered

having a file in every folder under workspace that contains the last modified timestamp or sha of the telefonistka.yaml.

```
version=$(shasum ./telefonistka.yaml)
echo $version
for subfolder in ./workspace/*/ ; do
    if [ -d "$subfolder" ]; then
        echo $version >  $subfolder'telefonistka-config-version.txt'
    fi
done
```

## Additional Context

Please provide any other information that may be relevant.

**Comment by Oded-B** [comment]
Interesting...
The hardest part would generatign the list of components to promote
Telefonistka isn't really aware of all the component paths in a folder - it looks at any file that was changed in  a PR  analyze it "on the spot".
I would have to get a list of all files under said `sourcePath`  and consider them as changed, as long as people don't have insanely big repos this should be ok

**Comment by Oded-B** [comment]
Tracking changes in the root `telefonistka.yaml` was also requested inhttps://github.com/wayfair-incubator/telefonistka/issues/105

**Comment by nielsole** [comment]
I'm gonna try the alternative considered for now and see if this is too much of a crutch.
