### ISSUE TITLE
Fast promotion flow usability

### ISSUE THREAD

**Issue by nielsole** [wayfair-incubator/telefonistka#23]
## Problem Statement

Currently a differing promotion flow is available for PRs that have specific tags (e.g. quick_promotion).
For me personally I only think about the promotion part after merging.
By this time it is too late to choose which promotion process to choose.

## Proposed Solution

I dont have a good solution handy. As quick promotion is probably the default for the majority of changes (as most changes are relatively trivial), while we dont want to have it as the default for safety reasons, it might be a sensible choice to make the user choose a promotion flow before merging. (blocking merging)

## Alternatives Considered

Offering funcitonality to consolidate promotion PRs after merging the main PR.

## Additional Context

Please provide any other information that may be relevant.

**Comment by Oded-B** [comment]
How about this: you'll add the label  to the already-merged PR and then comment something like `/re-promote-this-change`.

 Telefonistka will 
* Close all opened PR link to the merged PR( not sure how they will be found - hoping the "linked PRs" are available via the API)
* Restart the promotion process (taking in to account the added label )

**Comment by Oded-B** [comment]
These query + params can fetch linked PR, then I'll have to ensure those are "really" linked by checked their in-body metadata, and those who match I can close

```
query ($name: String!, $owner: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      number
      timelineItems(last: 100) {
        edges {
          node {
            ... on CrossReferencedEvent {
              source {
                ... on PullRequest {
                  number
                }
              }
              target {
                ... on PullRequest {
                  number
                }
              }
            }
          }
        }
      }
    }
  }
}
```


```
{
  "owner": "Oded-B",
  "name": "telefonistka-example",
  "number": 86
}
```
